# Generated by Django 6.0.2 on 2026-02-23 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('rooms', '0002_building_room_building_ref_floorplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('device_serial', models.CharField(help_text='Hardware serial or generated UUID from the tablet', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paired', 'Paired'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-set to created_at + 10 minutes')),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, help_text='Populated when an admin pairs the code to a room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_codes', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
