# Generated by Django 6.0.2 on 2026-02-16 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0002_building_room_building_ref_floorplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension_minutes', models.IntegerField(help_text='Number of minutes added to the booking')),
                ('extended_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when extension was granted')),
            ],
            options={
                'ordering': ['-extended_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this booking is part of a recurring series'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='For child bookings, reference to the parent booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Last date in the recurring series', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.JSONField(blank=True, help_text="JSON pattern details (e.g., {'days': [0,2,4], 'interval': 1})", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', help_text='Type of recurrence pattern (daily, weekly, monthly)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start_time'], name='bookings_bo_room_id_2520ec_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_time'], name='bookings_bo_status_3c2736_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['parent_booking'], name='bookings_bo_parent__2d389a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingattendee',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_d5e5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingattendee',
            index=models.Index(fields=['user'], name='bookings_bo_user_id_c8c1f9_idx'),
        ),
        migrations.AddField(
            model_name='bookingextension',
            name='booking',
            field=models.ForeignKey(help_text='The booking being extended', on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingextension',
            name='extended_by',
            field=models.ForeignKey(help_text='User who requested the extension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingextension',
            index=models.Index(fields=['booking', '-extended_at'], name='bookings_bo_booking_06e74a_idx'),
        ),
    ]
