# Generated by Django 6.0.2 on 2026-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_recurring_and_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendee_count',
            field=models.IntegerField(default=1, help_text='Number of expected attendees'),
        ),
    ]
