# Generated by Django 6.0.2 on 2026-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_attendee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='External calendar event ID (Google, Microsoft, Zoho, Exchange)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='calendar_provider',
            field=models.CharField(blank=True, help_text='Which calendar provider created/synced this event', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether a check-in reminder email has been sent for this booking'),
        ),
    ]
