# Generated by Django 6.0.2 on 2026-02-09 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
            },
        ),
    ]
