# Generated by Django 6.0.2 on 2026-02-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Circle Time', max_length=255)),
                ('primary_colour', models.CharField(default='#1E8ACC', help_text='Hex colour including #, e.g. #1E8ACC', max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checkin_window_minutes', models.IntegerField(default=15, help_text='Minutes before meeting start that attendees can check in')),
                ('auto_release_minutes', models.IntegerField(default=15, help_text='Minutes after meeting start before room is auto-released if no check-in')),
                ('business_days', models.JSONField(default=list, help_text='List of active day numbers (0=Mon, 6=Sun), e.g. [0,1,2,3,4]')),
                ('business_start', models.TimeField(default='08:00')),
                ('business_end', models.TimeField(default='17:00')),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation Settings',
            },
        ),
    ]
