# Generated by Django 6.0.2 on 2026-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsettings',
            name='logo_url',
            field=models.TextField(blank=True, help_text='URL or base64 data URI for the logo', null=True),
        ),
    ]
