# Generated by Django 6.0.2 on 2026-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_calendartoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
